spring:
  application:
    name: bank-account-system


  # PostgreSQL Configuration (for Users, Accounts, Roles)
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true  # Shows SQL queries in console (helpful for learning)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  # MongoDB Configuration (for Transaction History)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: banking_transactions
      # No username/password needed for local development

# Server Configuration
server:
  port: 8080

# Logging Configuration (helpful for debugging)
logging:
  level:
    com.banking.system: DEBUG  # Your package logs
    org.springframework.data.mongodb: DEBUG  # MongoDB logs
    org.hibernate.SQL: DEBUG  # SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL parameters

